import { business, faq, orderOptions, testimonials } from '../data/business';
import { messages, whatsappUrl } from '../utils/whatsapp';
export function About(){return <section id="sobre" className="about"><div className="about__image"><img src="https://images.unsplash.com/photo-1559620192-032c4bc4674e?auto=format&fit=crop&fm=webp&w=1000&q=80" alt="Foto ilustrativa de detalhes de confeitaria" loading="lazy"/><p>doce é afeto</p></div><div className="about__copy"><p className="eyebrow">A GEO DOCES</p><h2>Feito com carinho em cada detalhe.</h2><p>{business.brandStory || 'A Geo Doces nasceu para levar sabor, cuidado e capricho para cada pedido. Cada doce é preparado pensando não apenas no sabor, mas também na experiência de quem recebe.'}</p><p>Seja para matar aquela vontade de doce ou tornar uma ocasião ainda mais especial, cada encomenda é preparada com atenção e carinho.</p><a className="text-link" href="#galeria">Conhecer os doces <span>→</span></a></div></section>}
export function Orders(){return <section id="encomendas" className="orders"><div><p className="eyebrow">PEDIDOS ESPECIAIS</p><h2>Vai comemorar algo especial?</h2><p>Consulte as opções disponíveis para encomendas e deixe seu momento ainda mais doce.</p>{orderOptions.length > 0 && <div className="order-tags">{orderOptions.map(x=><span key={x}>{x}</span>)}</div>}<a className="button" href={whatsappUrl(messages.customOrder)} target="_blank" rel="noreferrer">Consultar encomenda <span>↗</span></a></div><div className="orders__mark">G<span>e</span>o</div></section>}
export function HowToOrder(){const steps=[['01','Escolha','Veja os produtos disponíveis.'],['02','Fale com a gente','Clique no WhatsApp e envie seu pedido.'],['03','Confirme','Combine disponibilidade, pagamento e entrega ou retirada.'],['04','Aproveite','Receba seu pedido e aproveite seu momento.']];return <section className="section how"><div className="section-heading"><p className="eyebrow">SIMPLES ASSIM</p><h2>Seu pedido em poucos passos.</h2></div><div className="steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
export function Benefits(){const values=[['Produção cuidadosa','Cada pedido preparado com atenção.'],['Apresentação','Cuidado também na estética e embalagem.'],['Atendimento próximo','Facilidade para tirar dúvidas e encomendar.'],['Momentos especiais','Produtos para tornar ocasiões mais gostosas.']]; return <section className="benefits"><div className="section-heading centered"><p className="eyebrow">O JEITO GEO DE FAZER</p><h2>Um doce especial começa nos detalhes.</h2></div><div>{values.map(([t,d])=><article key={t}><span>✦</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
export function ConditionalSections(){return <>{testimonials.length>0&&<section className="section"><div className="section-heading"><h2>Quem prova, recomenda.</h2></div></section>}{faq.length>0&&<section className="section faq"><div className="section-heading"><h2>Dúvidas antes do pedido?</h2></div>{faq.filter(x=>x.answer).map(x=><details key={x.question}><summary>{x.question}<span>+</span></summary><p>{x.answer}</p></details>)}</section>}{(business.deliveryEnabled||business.pickupEnabled)&&<section className="section delivery"><div className="section-heading"><h2>Como receber seu pedido.</h2></div>{business.deliveryEnabled&&<article><h3>Entrega</h3><p>{business.deliveryInfo}</p></article>}{business.pickupEnabled&&<article><h3>Retirada</h3><p>{business.pickupInfo}</p></article>}</section>}</>}
export function Instagram(){return <section className="instagram"><div><p className="eyebrow">ACOMPANHE A GEO</p><h2>Mais doces por lá.</h2><p>Novidades, inspirações e um pouco do carinho que vai em cada pedido.</p><a className="text-link" href={business.instagramUrl} target="_blank" rel="noreferrer">Seguir {business.instagram} <span>↗</span></a></div><div className="instagram__handle">{business.instagram}</div></section>}
export function FinalCTA(){return <section id="contato" className="final-cta"><p className="eyebrow">SEU MOMENTO MAIS DOCE COMEÇA AQUI</p><h2>Já escolheu seu doce?</h2><p>Fale com a Geo Doces pelo WhatsApp e consulte os sabores e produtos disponíveis.</p><a className="button button--light" href={whatsappUrl(messages.order)} target="_blank" rel="noreferrer">Fazer meu pedido <span>↗</span></a><small>Resposta e disponibilidade consultadas diretamente pelo WhatsApp.</small></section>}
